
language: cpp

os: linux
dist: trusty
sudo: false
compiler: gcc

cache: ccache

addons:
  apt:
    packages:
      - libboost-dev

script:
  - ./autogen.sh
  - ./configure --disable-static
  - ccache --print-config
  - ccache --zero-stats
  - ccache --max-size==1G
  - make -j 2 -C ql
  - make -j 2 -C Examples
  - ccache --show-stats

